### ISSUE TITLE
Declaration of verbb\buttonbox\fields\Width::translatedOptions....

### ISSUE THREAD

**Issue by adrianjean** [supercool/buttonbox#46]
**Description**
Latest Craft CMS update (3.7.46) might have broken Button Box plugin.
I'm getting the following error after upgrading: 

`Declaration of verbb\buttonbox\fields\Width::translatedOptions(): array should be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false): array
 `

At line 157 of `/vendor/verbb/buttonbox/src/fields/Width.php`

**Additional info**
- Plugin version: 3.0.2
- Craft version: 3.7.46
- Multi-site: Yes

**Comment by adrianjean** [comment]
Looks like `line 157`  of `/vendor/verbb/buttonbox/src/fields/Width.php` might need to change 

**from this**

`protected function translatedOptions(): array`

**to this** 

`protected function translatedOptions(bool $encode = false): array`

But... I'm not a plugin dev, so I don't know if that just messes something else up?

**Comment by adrianjean** [comment]
Issue shows up in other places as well:

`/vendor/verbb/buttonbox/src/fields/Colours.php — line 148`
`protected function translatedOptions(): array`

**Becomes:** 
`protected function translatedOptions(bool $encode = false): array`

And here: `/vendor/verbb/buttonbox/src/fields/TextSize.php — line 162`
`protected function translatedOptions(): array`

**Becomes:**
`protected function translatedOptions(bool $encode = false): array`

And here: `/vendor/verbb/buttonbox/src/fields/Buttons.php — line 200`
`protected function translatedOptions(): array`

**Becomes:** 
`protected function translatedOptions(bool $encode = false): array`

And here: `/vendor/verbb/buttonbox/src/fields/Triggers.php — line 170`
`protected function translatedOptions(): array`

**Becomes:** 
`protected function translatedOptions(bool $encode = false): array`

**Comment by engram-design** [comment]
Looks like this is indeed **very** fresh bug introduced in [Craft 3.7.46](https://github.com/craftcms/cms/blob/v3/CHANGELOG.md#changed). and Craft 4.1.0 today.

Fixed in [3.1.0](https://github.com/verbb/buttonbox/releases/tag/3.1.0) and [4.1.0](https://github.com/verbb/buttonbox/releases/tag/4.1.0).

**Comment by proimage** [comment]
@engram-design So how does one update Button Box? The plugin store shows 3.0.2 as the latest version available. Craft is at 3.7.41. When I change `verbb/buttonbox` to 3.1.0 in `composer.json` and run `composer install`, I get this:
```bash
  … checking /path/to/project/composer.json ✓
Loading composer repositories with package information
Cannot create cache directory /.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only.
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires verbb/buttonbox 3.1.0 -> satisfiable by verbb/buttonbox[3.1.0].
    - verbb/buttonbox 3.1.0 requires craftcms/cms ^3.7.46 -> found craftcms/cms[3.7.46, 3.7.47, 3.7.47.1] but it conflicts with your root composer.json require (3.7.41).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
composer update completed 🤘
```

I've tried updating the Craft version number similarly to 3.7.46 but then I get even more problems:
```
  Problem 1
    - Root composer.json requires craftcms/cms 3.7.46, found craftcms/cms[3.7.46] but the package is fixed to 3.7.41 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
  Problem 2
    - Root composer.json requires verbb/buttonbox 3.1.0 -> satisfiable by verbb/buttonbox[3.1.0].
    - verbb/buttonbox 3.1.0 requires craftcms/cms ^3.7.46 -> found craftcms/cms[3.7.46, 3.7.47, 3.7.47.1] but the package is fixed to 3.7.41 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```
I realize this is probably down to me just not fully grokking how to use composer properly, but I can't be the only one struggling with this, can I? How do I progress here? Thanks!

**Comment by engram-design** [comment]
Running a `composer update` if you prefer the command line, or `./craft update`, or using the CP to update should do the trick!

That's actually quite interesting about the plugin store, I might ping them about it. But according to Packigist, the 3.1.0 tag definitely exists.

But that error shows that you need Craft `3.7.46` or later. Normally, if you run any of the above commands, Composer will sort out the compatible versions, but if you're manually editing the composer required files - in your case, saying you need Buttonbox 3.1.0, but you also want Craft 3.7.41 it just won't work, because those two versions aren't compatible.

The resolution is to update Craft and Button Box together. How you do that depends on what you prefer to update Craft/plugins with.

If you like to edit via the `composer.json` file manually, the ensure you set:
```
"verbb/buttonbox": "^3.1.0",
"craftcms/cms": "^3.7.46",
```

And run `composer update`.

If you prefer the plugin store UI via the control panel or `./craft update` then Craft will sort out the latest versions for you.

**Comment by proimage** [comment]
Yeah, so obviously since the Plugin Store doesn't show the 3.1.0 update for BB, but it _does_ show Craft's updates, then when I've tried that, I get the error in the original post above.

Running `composer update` did the trick, thanks! Not sure how I didn't stumble across that before. 🤷‍♂️

**Comment by engram-design** [comment]
Weird! The plugin store does show `3.1.0` now and must've been some strange caching thing - despite the release being pushed 2 weeks ago. Glad you got it sorted.

And yeah, not sure if you were trying to update _just_ Button Box, or _just_ Craft, but you'll need to update everything in one go, as one relies on the other.
