### ISSUE TITLE
Botton box causing Craft CMS to crash

### ISSUE THREAD

**Issue by akdesign** [supercool/buttonbox#47]
**Description**
I ran a composer update to update Craft 3 CMS to 3.7.47; after the update was complete, my site was down, and I'm getting the error below from the CMS control panel. How can FIx this issue?

PHP Warning – [yii\base\ErrorException](http://www.yiiframework.com/doc-2.0/yii-base-errorexception.html)

Declaration of verbb\buttonbox\fields\Colours::translatedOptions(): array should be compatible with craft\fields\BaseOptionsField::translatedOptions(bool $encode = false): array

**Additional info**
- Plugin version: 3.0.2
- Craft version: 3.7.47
- Multi-site:  No

**Additional context**

**Comment by peteralewis** [comment]
I had this so reverted Craft CMS to v3.7.44 in the short run as it's a change in Craft that causes the error.

```
  "require": {
    "craftcms/cms": "3.7.44",
```

But that was because I couldn't work out how to get v3.1.0 as it seemed Packagist wasn't finding the latest version, then I realised I was still using supercool/buttonbox instead of verbb/buttonbox in my composer.

https://github.com/verbb/buttonbox/issues/46

You're using 3.0.2, but it was fixed in v3.1.0, so try that first and if all else fails revert the Craft version.

**Comment by engram-design** [comment]
Indeed, fixed in [3.1.0](https://github.com/verbb/buttonbox/releases/tag/3.1.0). This was due to a Craft change between Craft 3.7.45.2 and Craft 3.7.46 (refer to https://github.com/verbb/buttonbox/issues/46).

Generally speaking, it's good practice to update Craft and plugins at the same time.
